# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/settingswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(554, 218)
        font = QtGui.QFont()
        font.setPointSize(12)
        SettingsWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_files/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(SettingsWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MainButtonsLayout = QtWidgets.QHBoxLayout()
        self.MainButtonsLayout.setObjectName("MainButtonsLayout")
        self.ButtonSaveProfile = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonSaveProfile.sizePolicy().hasHeightForWidth())
        self.ButtonSaveProfile.setSizePolicy(sizePolicy)
        self.ButtonSaveProfile.setObjectName("ButtonSaveProfile")
        self.MainButtonsLayout.addWidget(self.ButtonSaveProfile)
        self.ButtonLoadProfile = QtWidgets.QPushButton(self.centralWidget)
        self.ButtonLoadProfile.setObjectName("ButtonLoadProfile")
        self.MainButtonsLayout.addWidget(self.ButtonLoadProfile)
        self.ButtonDeleteProfile = QtWidgets.QPushButton(self.centralWidget)
        self.ButtonDeleteProfile.setObjectName("ButtonDeleteProfile")
        self.MainButtonsLayout.addWidget(self.ButtonDeleteProfile)
        self.gridLayout.addLayout(self.MainButtonsLayout, 6, 0, 1, 5)
        self.MainTabBar = QtWidgets.QTabWidget(self.centralWidget)
        self.MainTabBar.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainTabBar.setIconSize(QtCore.QSize(20, 20))
        self.MainTabBar.setObjectName("MainTabBar")
        self.ServerTab = QtWidgets.QWidget()
        self.ServerTab.setObjectName("ServerTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ServerTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AuthLayout = QtWidgets.QHBoxLayout()
        self.AuthLayout.setObjectName("AuthLayout")
        self.InputServerAddress = QtWidgets.QLineEdit(self.ServerTab)
        self.InputServerAddress.setReadOnly(False)
        self.InputServerAddress.setObjectName("InputServerAddress")
        self.AuthLayout.addWidget(self.InputServerAddress)
        self.InputPort = QtWidgets.QLineEdit(self.ServerTab)
        self.InputPort.setObjectName("InputPort")
        self.AuthLayout.addWidget(self.InputPort)
        self.InputUsername = QtWidgets.QLineEdit(self.ServerTab)
        self.InputUsername.setObjectName("InputUsername")
        self.AuthLayout.addWidget(self.InputUsername)
        self.gridLayout_2.addLayout(self.AuthLayout, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SSLCheckBox = QtWidgets.QCheckBox(self.ServerTab)
        self.SSLCheckBox.setObjectName("SSLCheckBox")
        self.horizontalLayout.addWidget(self.SSLCheckBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.ConnectionButtons = QtWidgets.QHBoxLayout()
        self.ConnectionButtons.setContentsMargins(-1, 0, -1, -1)
        self.ConnectionButtons.setObjectName("ConnectionButtons")
        self.ButtonStartConnection = QtWidgets.QPushButton(self.ServerTab)
        self.ButtonStartConnection.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ButtonStartConnection.setObjectName("ButtonStartConnection")
        self.ConnectionButtons.addWidget(self.ButtonStartConnection)
        self.ButtonEndConnection = QtWidgets.QPushButton(self.ServerTab)
        self.ButtonEndConnection.setObjectName("ButtonEndConnection")
        self.ConnectionButtons.addWidget(self.ButtonEndConnection)
        self.gridLayout_2.addLayout(self.ConnectionButtons, 6, 0, 1, 1)
        self.MainTabBar.addTab(self.ServerTab, "")
        self.gridLayout.addWidget(self.MainTabBar, 2, 0, 1, 5)
        SettingsWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(SettingsWindow)
        self.MainTabBar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.ButtonSaveProfile.setText(_translate("SettingsWindow", "Save Profile"))
        self.ButtonLoadProfile.setText(_translate("SettingsWindow", "Load Profile"))
        self.ButtonDeleteProfile.setText(_translate("SettingsWindow", "Delete Profile"))
        self.InputServerAddress.setToolTip(_translate("SettingsWindow", "Hostname of the server"))
        self.InputServerAddress.setPlaceholderText(_translate("SettingsWindow", "Hostname"))
        self.InputPort.setPlaceholderText(_translate("SettingsWindow", "Port"))
        self.InputUsername.setToolTip(_translate("SettingsWindow", "Your Username to connect to the chat-server"))
        self.InputUsername.setPlaceholderText(_translate("SettingsWindow", "Username"))
        self.SSLCheckBox.setText(_translate("SettingsWindow", "Use SSL"))
        self.ButtonStartConnection.setToolTip(_translate("SettingsWindow", "Establish a Connection to the Server with the provided informaiton"))
        self.ButtonStartConnection.setText(_translate("SettingsWindow", "Connect"))
        self.ButtonEndConnection.setToolTip(_translate("SettingsWindow", "Disconnect from the Serve, abort connection"))
        self.ButtonEndConnection.setText(_translate("SettingsWindow", "Disconnect"))
        self.MainTabBar.setTabText(self.MainTabBar.indexOf(self.ServerTab), _translate("SettingsWindow", "Server"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
